concurrency:
  cancel-in-progress: true
  group: ci-buildcache-${{ github.ref }}
jobs:
  check_secrets:
    env:
      S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
      S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
    name: Check if required secrets are available
    outputs:
      secrets_available: ${{ steps.set-matrix.outputs.secrets_available }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: set-matrix
      run: "if [[ -n \"${S3_BUILD_CACHE_ACCESS_KEY_ID:-}\" ]] && [[ -n \"${S3_BUILD_CACHE_SECRET_KEY:-}\"\
        \ ]]; then\n  echo \"secrets_available=true\" >> $GITHUB_OUTPUT\nelse\n  echo\
        \ \"secrets_available=false\" >> $GITHUB_OUTPUT\nfi\n"
  seed-build-cache:
    if: ${{ needs.check_secrets.outputs.secrets_available == 'true' }}
    name: ${{ matrix.os }}, ${{ matrix.jdk }} seed build cache
    needs: check_secrets
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 50
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: liberica
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      env:
        S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
        S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
      name: Build pgjdbc
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: build -x test --scan -i
        job-id: jdk${{ matrix.jdk }}
    strategy:
      matrix:
        jdk:
        - 17
        os:
        - ubuntu
        - macos
        - windows
name: Seed build cache
on:
  repository_dispatch:
    types: trigger-ga___buildcache.yml
permissions:
  contents: read
