jobs:
  snapshot:
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Debezium
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 50
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Publish Snapshot
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: postgresql:publishToMavenLocal -Ppgjdbc.version=1.0.0-dev-master
          -PskipJavadoc
        job-id: jdk8
    - continue-on-error: true
      name: clone debezium and run tests
      run: 'git clone --depth 1 https://github.com/debezium/debezium.git

        cd debezium

        mvn clean verify -pl :debezium-connector-postgres -am -Dversion.postgres.server=14
        -Dversion.postgresql.driver=1.0.0-dev-master-SNAPSHOT

        '
name: Test Debezium
on:
  repository_dispatch:
    types: trigger-ga___debezium.yml
permissions:
  contents: read
