jobs:
  build:
    name: Submit a Copr build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out proper version of sources
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        COPR_PR_WEBHOOK: https://copr.fedorainfracloud.org/webhooks/custom/55296/cf449c12-03b4-4f5b-ae84-3f5aa1d2b462/postgresql-jdbc/
        COPR_PUSH_WEBHOOK: ${{ secrets.COPR_PUSH_WEBHOOK }}
      name: Submit the build
      run: 'curl https://raw.githubusercontent.com/praiskup/copr-ci-tooling/main/copr-gh-actions-submit
        > submit

        bash submit ${{ github.event.pull_request.number }}

        '
name: RPM build in Fedora Copr
on:
  repository_dispatch:
    types: trigger-ga___fedora-copr-build.yml
permissions:
  contents: read
